//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMedicationOrder
    {
        public int intMedicationOrderID { get; set; }
        public Nullable<int> intMedicationID { get; set; }
        public string strMedicationName { get; set; }
        public Nullable<System.DateTime> dtmOrderDate { get; set; }
        public Nullable<decimal> dblUnitCost { get; set; }
        public Nullable<int> intOrderQuantity { get; set; }
        public Nullable<decimal> dblTotal { get; set; }
        public string strNotes { get; set; }
    
        public virtual TMedication TMedication { get; set; }
    }
}
