//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TPet {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPet() {
            this.TPetImages = new HashSet<TPetImage>();
            this.TVisits = new HashSet<TVisit>();
        }

        public int intPetID { get; set; }

        public string strPetNumber { get; set; }

        public string strMicrochipID { get; set; }
        [Required(ErrorMessage = "Pet Name is required")]
        public string strPetName { get; set; }
        [Required(ErrorMessage = "Pet Type is required")]
        public int intPetTypeID { get; set; }
        [Required(ErrorMessage = "Gender is required")]
        public int intGenderID { get; set; }
        [Required(ErrorMessage = "Breed is required")]
        public int intBreedID { get; set; }
        [Required(ErrorMessage = "DOB is required")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime dtmDateofBirth { get; set; }
        
        [Required(ErrorMessage = "Weight is required")]
        public double dblWeight { get; set; }

        public bool isBlind { get; set; }

        public bool isDeaf { get; set; }
        public bool isAggressive { get; set; }
        public bool isDeceased { get; set; }
        public bool isAllergic { get; set; }
        [Required]
        public string strColor { get; set; }

        public string strNotes { get; set; }
        [Required(ErrorMessage = "Owner is required")]
        public int intOwnerID { get; set; }

        public virtual TBreed TBreed { get; set; }
        public virtual TGender TGender { get; set; }
        public virtual TOwner TOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPetImage> TPetImages { get; set; }
        public virtual TPetType TPetType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVisit> TVisits { get; set; }
        public object TPetImage { get; internal set; }
    }
}
