//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVisitNote
    {
        public int intVisitNotesID { get; set; }
        public string strVisitNotes { get; set; }
        public Nullable<int> intVisitID { get; set; }
    
        public virtual TVisit TVisit { get; set; }
    }
}
